name: Kenner Wire and Cable
favicon: null
layout_spectrum: 0.5893617
typography_spectrum: 0.3191489
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Your Wire and Cable System Solutions Source
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.240709978621453
  lightness: 1
  saturation: 0.7361702
  rhythmicContrast: 0.8276595
purpose: []
