name: Kenner Wire and Cable
favicon: null
layout_spectrum: 0.02185240900143981
typography_spectrum: 0.5236821186263114
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24070997862145305
  lightness: 0.5922951409593225
  saturation: 0.8937691191677004
  rhythmicContrast: 0.9934768062084913
purpose: []
